services:
  compile:
    extends:
      file: docker/common.yaml
      service: build
    profiles: [optional]
    command: 'colcon --log-base /dev/null build --symlink-install --event-handlers event_log- log-'

  bash:
    extends:
      file: docker/common.yaml
      service: x11_base
    profiles: [optional]
    command: 'bash --rcfile /etc/bash.bashrc'
