services:
  compile:
    <<: *build
    command: 'colcon --log-base /dev/null build --symlink-install --event-handlers event_log- log-'

  bash:
    <<: *x11
    volumes:
      - $HOME/data:$HOME/data
    command: 'bash --rcfile /etc/bash.bashrc'
