services:
  compile:
    extends:
      file: docker/${TIRREX_IMAGE_TAG}.yaml
      service: build
    command: colcon --log-base /dev/null build --symlink-install --event-handlers event_log- log-

  bash:
    extends:
      file: docker/${TIRREX_IMAGE_TAG}.yaml
      service: x11_base
    profiles: [optional]
    command: bash --rcfile /etc/bash.bashrc
