# This file should be extended by compose.yaml that want to use the devel version of the tirrex
# workspace. It defines the TIRREX_WORKSPACE environment variable and include the directory of this
# workspace as a volume. This workspace is used as underlay instead of the default /opt/tirrex_ws.
# To use it, you have to change the following variables in the .env file at the root of this
# workspace:
# TIRREX_WORKSPACE=<path/to/tirrex/workspace>
# TIRREX_IMAGE_TAG=devel


# define YAML anchors to factorize some elements to add in all services
x-anchors:
  common: &common  # the content of this block will be added every time there is a '*common'
    volumes:
      - ${TIRREX_WORKSPACE}:${TIRREX_WORKSPACE}:Z  # extend tirrex_workspace
    environment:
      - TIRREX_WORKSPACE  # used in /ros_setup.sh to extend the specified workspace
    image: ${IMAGE_NAME}
    

services:
  base:  # basic docker config to open a shell in the ROS environment
    <<: *common
    extends:  # the real docker configuration is in common.yaml from tirrex_workspace
      file: common.yaml
      service: base

  build:  # build the docker image using the Dockfile of this workspace
    <<: *common
    extends:
      service: base
    build:
      context: ../
      ssh: [default]
      args:
        FROM_IMAGE: ${FROM_IMAGE:-ghcr.io/tirrex-roboterrium/tirrex_workspace}:devel
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
        HOME: ${HOME}

  x11_base:  # add params to start graphical programs
    <<: *common
    extends:
      file: common.yaml
      service: x11_base

  x11_gpu:  # add params to use nvidia GPU (based on x11_base)
    <<: *common
    extends:
      file: common.yaml
      service: x11_gpu

  x11_robot:  # add params to open graphical programs through ssh
    <<: *common
    extends:
      file: common.yaml
      service: x11_robot
