# This file will be extended by compose.yaml to use the full version of the tirrex docker image.
# In this version, the tirrex_workspaceis already compiled and installed in /opt/tirrex_ws
# The environment variable TIRREX_WORKSPACE corresponds to this path.

# define YAML anchors to factorize some elements to add in all services
x-anchors:
  common: &common  # the content of this block will be added every time there is a '*common'
    environment:
      - TIRREX_WORKSPACE=/opt/tirrex_ws  # override value of .env to make it empty
    image: ${IMAGE_NAME}
    

services:
  base:  # basic docker config to open a shell in the ROS environment
    <<: *common
    extends:  # the real docker configuration is in common.yaml from tirrex_workspace
      file: common.yaml
      service: base

  build:  # build the docker image using the Dockfile of this workspace
    <<: *common
    extends:
      service: base
    build:
      context: ../
      args:
        FROM_IMAGE: ${FROM_IMAGE:-ghcr.io/tirrex-roboterrium/tirrex_workspace}:full
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
        HOME: ${HOME}

  x11_base:  # add params to start graphical programs
    <<: *common
    extends:
      file: common.yaml
      service: x11_base

  x11_gpu:  # add params to use nvidia GPU (based on x11_base)
    <<: *common
    extends:
      file: common.yaml
      service: x11_gpu

  x11_robot:  # add params to open graphical programs through ssh
    <<: *common
    extends:
      file: common.yaml
      service: x11_robot
