#!/bin/bash
REPOS_FILE='repositories'

set -e
cd "$(dirname -- "${BASH_SOURCE[0]}")/.."

# load variables, except UID and GID in .env to set correct value of REPOS_FILE
if [[ -r '.env' ]] ; then
    eval $(grep -v '^[UG]ID=' .env)
fi

import_packages() {
    echo 'Import packages'
    if [[ -r "docker/$REPOS_FILE" ]] ; then
      vcs import --recursive -w6 <"docker/$REPOS_FILE"
    else
      echo "  Nothing to do: there is no file 'docker/$REPOS_FILE'."
    fi
}


./scripts/create_env
import_packages
echo 'Installation completed successfully'
