#!/bin/bash

tirrex='https://raw.githubusercontent.com/Tirrex-Roboterrium/tirrex_workspace/refs/heads/main/'
template='https://raw.githubusercontent.com/Tirrex-Roboterrium/template_ws/refs/heads/main/'

ws_dir="$(dirname -- "${BASH_SOURCE[0]}")/.."
self_script=$(realpath --relative-to "$ws_dir" "${BASH_SOURCE[0]}")

cd "$ws_dir"

update_git_file() {
  prefix="$1"
  file="$2"

  if ! git diff --quiet "$file" ; then
    echo >&2 -n "There is local changes in '$file'. Override? [y/N]: "
    read choice
    if ! [[ "$choice" = 'Y' || "$choice" = 'y' ]] ; then
      return 2
    fi
  fi

  if ! curl -fso "$file" "${prefix}${file}" ; then
    echo >&2 "  -> failed to download $file"
    return 2
  fi

  # Execute again git diff to return 0 if the file has changed
  if git diff --quiet "$file" ; then
    echo "Updated: $file"
    return 0
  fi
  return 1
}

# if this script is updated, it is re-executed to take into account new 'update_git_file' lines
if [[ -z "${SELF_UPDATE}" ]] && update_git_file "$template" "$self_script" ; then
  echo "Rerun $self_script"
  SELF_UPDATE=1 exec "$self_script"
fi

update_git_file "$tirrex" docker/common.yaml
update_git_file "$tirrex" docker/cyclonedds_localhost.xml
update_git_file "$template" .devcontainer/devcontainer.json
update_git_file "$template" scripts/autosync_ws
update_git_file "$template" scripts/create_env
update_git_file "$template" scripts/create_ws
update_git_file "$template" scripts/sync_data

exit 0
